!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 35, y: 0, z: 5}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 5, y: 0, z: 35}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
