!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 35, y: 0, z: 5}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 33, y: 0, z: 15}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
