!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 5, y: 0, z: 35}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 15, y: 0, z: 25}
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5}
