!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 300
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: GoodGoal 
      positions:
      - !Vector3 {x: -1, y: 4, z: -1}
      - !Vector3 {x: -1, y: 4, z: -1}
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: -1, y: 0, z: -1} 
      - !Vector3 {x: -1, y: 0, z: -1} 
      - !Vector3 {x: -1, y: 10, z: -1} 
      - !Vector3 {x: -1, y: 10, z: -1} 
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1} 
      - !Vector3 {x: -1, y: -1, z: -1} 
      - !Vector3 {x: -1, y: -1, z: -1} 
      - !Vector3 {x: -1, y: -1, z: -1}  
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}