!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 300
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1]
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1}