!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 20}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 20, y: 0.5, z: 20}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 29, y: 1, z: 20}
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5}
