!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 5}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 4} 
      - !Vector3 {x: 18.5, y: 0, z: 21} 
      - !Vector3 {x: 21.5, y: 0, z: 21} 
      rotations: [0,0,0]
      sizes:
      - !Vector3 {x: 2, y: 0.5, z: 1}
      - !Vector3 {x: 1, y: 0.5, z: 35}
      - !Vector3 {x: 1, y: 0.5, z: 35}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [180]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}  
