!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 18, y: 0, z: 18}
      - !Vector3 {x: 18, y: 0, z: 20}
      - !Vector3 {x: 18, y: 0, z: 22}
      - !Vector3 {x: 20, y: 0, z: 18}
      - !Vector3 {x: 20, y: 0, z: 22}
      - !Vector3 {x: 22, y: 0, z: 18}
      - !Vector3 {x: 22, y: 0, z: 20}
      - !Vector3 {x: 22, y: 0, z: 22}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
      - !Vector3 {x: 1, y: 1, z: 1}  
