!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 20, y: 0, z: 25}
      - !Vector3 {x: 25, y: 0, z: 15}
      - !Vector3 {x: 30, y: 0, z: 25}
      rotations: [0,0,0,0]
      sizes:
      - !Vector3 {x: 3, y: 0, z: 30}
      - !Vector3 {x: 3, y: 0, z: 30}
      - !Vector3 {x: 3, y: 0, z: 30}
      - !Vector3 {x: 3, y: 0, z: 30}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 35, y: 0, z: 20}      
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 5, y: 0, z: 20}
      rotations: [90]