!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 35, y: 1, z: 5}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 29, y: 0, z: 11}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 20, y: 0.5, z: 20}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 33, y: 1, z: 7}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
